INSERT INTO modules (Name, Active) VALUES ('bigbrain', 'Y');
INSERT INTO modules (Name, Active) VALUES ('brainclassifiedvolumes', 'Y');
INSERT INTO modules (Name, Active) VALUES ('brainsurfaces', 'Y');
INSERT INTO modules (Name, Active) VALUES ('brainvolumes', 'Y');
INSERT INTO modules (Name, Active) VALUES ('contact', 'Y');
INSERT INTO modules (Name, Active) VALUES ('faq', 'Y');
INSERT INTO modules (Name, Active) VALUES ('license', 'Y');
INSERT INTO modules (Name, Active) VALUES ('references', 'Y');
INSERT INTO modules (Name, Active) VALUES ('videos', 'Y');
UPDATE modules SET Active = 'N' WHERE Name = 'behavioural_qc';
UPDATE modules SET Active = 'N' WHERE Name = 'bvl_feedback';
UPDATE modules SET Active = 'N' WHERE Name = 'behavioural_qc';
UPDATE modules SET Active = 'N' WHERE Name = 'candidate_list';
UPDATE modules SET Active = 'N' WHERE Name = 'candidate_parameters';
UPDATE modules SET Active = 'N' WHERE Name = 'conflict_resolver';
UPDATE modules SET Active = 'N' WHERE Name = 'create_timepoint';
UPDATE modules SET Active = 'N' WHERE Name = 'data_release';
UPDATE modules SET Active = 'N' WHERE Name = 'datadict';
UPDATE modules SET Active = 'N' WHERE Name = 'dataquery';
UPDATE modules SET Active = 'N' WHERE Name = 'dicom_archive';
UPDATE modules SET Active = 'N' WHERE Name = 'document_repository';
UPDATE modules SET Active = 'N' WHERE Name = 'examiner';
UPDATE modules SET Active = 'N' WHERE Name = 'genomic_browser';
UPDATE modules SET Active = 'N' WHERE Name = 'help_editor';
UPDATE modules SET Active = 'N' WHERE Name = 'imaging_browser';
UPDATE modules SET Active = 'N' WHERE Name = 'imaging_qc';
UPDATE modules SET Active = 'N' WHERE Name = 'imaging_uploader';
UPDATE modules SET Active = 'N' WHERE Name = 'instrument_builder';
UPDATE modules SET Active = 'N' WHERE Name = 'instrument_list';
UPDATE modules SET Active = 'N' WHERE Name = 'instrument_manager';
UPDATE modules SET Active = 'N' WHERE Name = 'instruments';
UPDATE modules SET Active = 'N' WHERE Name = 'issue_tracker';
UPDATE modules SET Active = 'N' WHERE Name = 'media';
UPDATE modules SET Active = 'N' WHERE Name = 'mri_violations';
UPDATE modules SET Active = 'N' WHERE Name = 'new_profile';
UPDATE modules SET Active = 'N' WHERE Name = 'next_stage';
UPDATE modules SET Active = 'N' WHERE Name = 'publication';
UPDATE modules SET Active = 'N' WHERE Name = 'server_processes_manager';
UPDATE modules SET Active = 'N' WHERE Name = 'statistics';
UPDATE modules SET Active = 'N' WHERE Name = 'survey_accounts';
UPDATE modules SET Active = 'N' WHERE Name = 'timepoint_list';
UPDATE modules SET Active = 'N' WHERE Name = 'battery_manager';
UPDATE modules SET Active = 'N' WHERE Name = 'electrophysiology_browser';
UPDATE modules SET Active = 'N' WHERE Name = 'candidate_profile';

